name: Run Unit + E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests unitarios
        run: npm run test

      - name: Ejecutar tests E2E (Playwright)
        run: |
          npx playwright install --with-deps
          npx playwright test
